### PR TITLE
use AbstractArray for refs

### PR DESCRIPTION
**Pull request by shashi**
Would it benefit from having another type parameter (type of the array)?

### CODE REVIEW

**Comment by JeffBezanson** [comment]
Yes, I'm pretty sure the type would need to be specialized on this.

**Comment by shashi** [comment]
Done. While I'm here I've sneaked in a refactoring I need in TextParse to avoid allocation of strings unless not present in pool.

**Comment by shashi** [comment]
Don't merge this, I am trying to avoid needing the first commit. Once done, I'll remove it and merge this.

**Comment by JeffBezanson** [comment]
Is this ready to squash and merge?

**Comment by shashi** [comment]
Yes. the 5 commits do separate things, so you might just want to merge it.

**Pull request merged**
