### PR TITLE
delete extension of ipermute!!

### PR DESCRIPTION
**Pull request by kafisatz**
ipermute!! does not seem to exist in  v 0.7

### CODE REVIEW

**Comment by swt30** [comment]
`ipermute` and related methods are called `invpermute` in 0.7 (see https://github.com/JuliaLang/julia/pull/25168).

**Comment by kafisatz** [comment]
indeed. I will close this.

**Comment by swt30** [comment]
I think the best thing to do is to wait for [femtocleaner](https://github.com/JuliaComputing/FemtoCleaner.jl) to be ready for 0.7, which should be very soon. Then changes like this can all be done at once :)

**Comment by kafisatz** [comment]
@swt30 Funny that you should mention that. I am actually trying to get FemtoCleaner working LOCALLY on either 0.6.3 or 0.7alpha. I am failing at both, although I thought that it would at least work on 0.6.3 somehow.

**Comment by swt30** [comment]
@kafisatz [My fork](https://github.com/swt30/PooledArrays.jl) has a branch updated to remove deprecation warnings so that this works on julia 0.7. You can try it by doing `add https://github.com/swt30/PooledArrays.jl.git#julia-0.7` at the pkg prompt if you like.

**Comment by kafisatz** [comment]
Thank you

**Comment by swt30** [comment]
A new tag was just merged here with 0.7 support so I'm deleting that fork and switching back to this repo :)

**Pull request closed without merging**
