### PR TITLE
Dict pool

### PR DESCRIPTION
**Pull request by shashi**
Has the same performance characters as the previous version for sort.

Provides much better scaling when there are millions of uniques.

### CODE REVIEW

**Comment by matthieugomez** [comment]
Out of curiosity, does not that make iterating over a PooledArray much slower (dictionary indexing vs vector indexing, no possibility for SIMD when iterating over a PooledArray, etc)?

**Comment by shashi** [comment]
Not necessarily. Before this change indexing was `O(log(k))` where k is length of pool, now it is `O(1)`. Simd wouldn't be applicable since each iteration would do a binary search over the pool.

**Comment by matthieugomez** [comment]
Sorry I still don't understand.  The [pull request](https://github.com/JuliaComputing/PooledArrays.jl/pull/5/files#diff-c71fbed882fca032abf2f68c03cbcad5L292) transformed indexing from a simple array indexing lookup to a dictionary key lookup, right? Isn't array indexing usually much faster?

**Comment by nalimilan** [comment]
Actually @bkamins just filed https://github.com/JuliaComputing/PooledArrays.jl/issues/14 because we didn't understand why a `Dict` is used here. This doesn't make any sense to me: we know references are integers in the `1:length(x.pool)` range, so the most efficient structure to lookup a value is clearly a vector. There's no binary search involved.

What could make sense is to keep  an inverted pool around as a `Dict` to speed up other operations (like `CategoricalArrays` do), but that doesn't mean the `Vector` pool should be removed.

**Comment by bkamins** [comment]
Also to add to what @nalimilan pointed out (i.e. that it would be good to have a `Vector` and a `Dict` not two `Dict`s) there is plenty of functionality in CategoricalArrays.jl that I think could be simply ported to this package (optimized support for a wider list of standard functions from Base or something like `CategoricalArrays.compress` which would be handy when there are a lot of `setindex!` operations on pooled array).

**Comment by shashi** [comment]
@matthieugomez you're right, thanks! I think changing `revpool` to a vector would bring back the lost performance.

**Pull request merged**
